#pragma once

typedef enum _PNP_INTERFACE_CHANGE_TYPE {
	PNP_INTERFACE_ARRIVAL,
	PNP_INTERFACE_REMOVAL,
	PNP_INTERFACE_CUSTOM
} PNP_INTERFACE_CHANGE_TYPE;

typedef void (*PNPBRIDGE_NOTIFY_DEVICE_CHANGE)(PPNPBRIDGE_DEVICE_CHANGE_PAYLOAD DeviceChangePayload);

typedef int(*START_DISCOVER)(PNPBRIDGE_NOTIFY_DEVICE_CHANGE DeviceChangeCallback, JSON_Object* deviceArgs, JSON_Object* adapterArgs);
typedef int(*STOP_DISCOVERY)();

typedef struct _DISCOVERY_ADAPTER {
    const char* Identity;
	START_DISCOVER StartDiscovery;
	STOP_DISCOVERY StopDiscovery;
} DISCOVERY_ADAPTER, *PDISCOVERY_ADAPTER;

int GetDiscoveryModuleInfo(PDISCOVERY_ADAPTER DiscoryInterface);

PNPBRIDGE_RESULT PnpBridge_DeviceChangeCallback(PPNPBRIDGE_DEVICE_CHANGE_PAYLOAD DeviceChangePayload);