#!/bin/sh
if [ -d "$cust_dir/logs" ] 
then
    echo "/logs directory already exists.  Using for new log files."
else
    mkdir $cust_dir/logs
fi

{
event=$1
echo "cust upgrade script enters"
echo "my SOP version is $primary_sop_vsn"
echo "my CAP version is $primary_cap_vsn"
test ! -z $secondary_sop_vsn && echo "There is an old SOP of version $secondary_sop_vsn"
test ! -z $secondary_cap_vsn && echo "There is an old CAP of version $secondary_cap_vsn"
if [ $event = "cdr" ] ; then
    echo "Reader restored its default configuration"

    # do something
elif [ $event = "upg" ] ; then
    echo "Reader just had an upgrade"
    echo "My old CAP version is $secondary_cap_vsn"
    cust_dir=$2
    old_cust_dir=$3

# copy some config from old app
    if [ -f $old_cust_dir/azure_pnpbridge/config.json ] ; then
       cp -f $old_cust_dir/azure_pnpbridge/config.json $cust_dir/azure_pnpbridge/config.json
    fi
fi
} > $cust_dir/logs/$(date +"%Y%m%d_%H%M%S")_cust_app_upgrade.log 2> $cust_dir/logs/$(date +"%Y%m%d_%H%M%S")_cust_app_upgrade_error.log