#!/bin/bash

if [ -f /cust/azure_pnpbridge/config.json ] ; then
    /cust/azure_pnpbridge/support_files/config_update-arm /cust/azure_pnpbridge/config.json /cust/azure_pnpbridge/config.json
fi

while true; do
    /cust/azure_pnpbridge/pnpbridge_bin /cust/azure_pnpbridge/config.json
    sleep 1
done
